# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  windows-build:
    executor:
      name: win/default
      shell: powershell
    steps:
      - checkout
      - run:
          name: Install Clang
          command: choco install llvm
      - run:
          name: Install CMake v3.20.1
          command: choco install cmake --version 3.20.1
      - run:
          name: Install Vcpkg
          command: git clone https://github.com/microsoft/vcpkg.git vcpkg
      - run:
          name: Reset to correct vcpkg version
          command: |
            cd vcpkg
            git reset --hard 807a79876
            cd ..
      - run:
          name: Bootstrap vcpkg
          command: ./vcpkg/bootstrap-vcpkg.bat -disableMetrics
      - run:
          name: Install dependencies
          no_output_timeout: 30m
          command: ./vcpkg/vcpkg install qt5-base qt5-svg msgpack boost-process fmt catch2
      - run:
          name: Make directory and CMake files in release mode
          command: |
            mkdir -p build
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
      - run:
          name: Build app and tests
          command: |
            cmake --build . --target nvui
            cmake --build . --target nvui_test
      - run:
          name: Run tests
          command: ./nvui_test
workflows:
  # Name the workflow "welcome"
  version: 2
  build:
    jobs:
      - windows-build
